### ISSUE TITLE
question about 0.10 releases status

### ISSUE THREAD

**Issue by pmeyerson** [Kintyre/ksconf#93] opened 2022-12-16 01:19 UTC
Hi, I've been using ksconf in my splunk app ci, thanks for making such a useful tool!

I notice that pypi only has the 0.10 releases, but they are marked pre-release.... are these stable at all?  Particularly interested in package and combine commands. Or would you recommend pulling 0.9x from github to use?  Thanks for clarifying!

**Comment by lowell80** [comment] 2022-12-20 15:12
Thanks for the question.  Unfortunately, I've been pulled in other directions recently and haven't had as much time to commit to new features on ksconf.  So sorry for the confusion my delay has caused.  That being said, I am hoping to get an official 0.10 release out there soon.

The biggest changes in 0.10 are under the covers and mostly have to do with packaging and Python 3 (only) support.  I've been using 0.10-beta4 in several production workflows for quite some time now without any issues.  

One of the things I was hoping to improve before dropping 0.10 was the upgrade path between 0.9 and 0.10.   Due to a python package rename, the in-place upgrade was causing some issues (fixed by an explicit uninstall/re-install).   I kinda hit a dead end there and that partially kept me from pulling the trigger on the new release. (I'm by no means a python packaging expert, and I really hate things that break especially on the "normal path")

There are some internal improvements to combine in 0.10, but I don't think you'll see a difference (other than maybe it's a touch faster?)

My recommendation would be to go with 0.10b4, which already has the new long-term package name (so you won't have to deal with any of that in the future):

    pip install ksconf==0.10b4

There isn't much need to pull from git, unless you plan on developing/contributing (which, of course, I'd welcome if you come across fixes/improvements.)

**Comment by lowell80** [comment] 2022-12-20 15:15
Oh, and I try to keep the change log up-to-date as I develop changes (though sometimes I do forget and then there's a flurry of changes right before a release).  

https://github.com/Kintyre/ksconf/blob/devel/docs/source/changelog.rst

otherwise I lose track :-)

**Comment by pmeyerson** [comment] 2022-12-20 16:05
Really appreciate the response, looks like .10b4 is working for me too without issues =)

BTW what was the package you need ignored in .10, Im definitly not expert either but maybe heads+1 will be better

**Comment by lowell80** [comment] 2022-12-20 16:51
Copying from the release notes:

> The official Python package was renamed `ksconf`. The `kintyre-splunk-conf` package continue to be released in parallel at least until version 1.0. You can continue updating the `kintyre-splunk-conf` package and it will install the `ksconf` package as a dependency.

That's how I *want* it to work, The older `kintyre-splunk-conf` becomes a "stub" that simply causes the newer `ksconf` package to be installed.  However what happens is that the pip package inventory shows that it `kintyre-splunk-conf` was updated and `ksconf` was installed (both which show the same version #), but the act of upgrades cause things to break. 
 I think it's because the same file are involved with both, so pip seems to get confused about which app owns the files. 
 The end result is that all of the shared `*.py` files (which is 90%+ of the code base) is missing in the installation folder.   Forcing a re-install fixes it.  (So the default behavior of simply running `pip install -U kintyre-splunk-conf` results in the executable breaking.).  I couldn't find any other python packages out there that have done this kind of thing and how they've gotten around this problem.

My other approach is to release both packages with identical content (other than package metadata, of course), and force users to manually switch between to the new package name eventually.  I don't really like this approach as much, but I guess it's better than breaking existing installs.

**Comment by lowell80** [comment] 2022-12-20 17:20
ugh, I just tried this again and pip either fixed the bug, or I'm loosing my mind.  lol

**Comment by pmeyerson** [comment] 2022-12-20 17:39
"all problems are solved with effort or time"

**Comment by lowell80** [comment] 2022-12-20 19:12
Yeah, I botched my first attempt to reproduce.  It *is* still broken.  Moved to #94.

Closing this issue.

**Closed as completed by lowell80** 2022-12-20 19:12 UTC
Labels: question
