### ISSUE TITLE
Unhandled top-level exception. UTF-8-BOM

### ISSUE THREAD

**Issue by SID800** [Kintyre/ksconf#61] opened 2019-10-04 23:03 UTC
**Env:**
ksconf 0.7.7rc1
Windows

**Issue:**
Looks like combine is possibly choking on the UTF-8-BOM characters?  Yea, probably should change that to ASCII or just UTF-8 anyways... but hey, maybe this one is actually a bug? ;) 

CLI output:
```
C:\Temp\TA_windows>ksconf combine * --target=default
Combining conf files into directory default
Reading conf files from directory my-org
Reading conf files from directory src
Creating destination directory default
Copy <created>   default\README.txt                                  from src\README.txt
Copy <created>   default\README\inputs.conf.spec                     from src\README\inputs.conf.spec
<snip>
Copy <created>   default\license-eula.txt                            from src\license-eula.txt
Merge <created>   default\local\app.conf                              from ['my-org\\local\\app.conf']
Unhandled top-level exception.  Unexpected entry:  u'\xef\xbb\xbf###################################'
```

The file isnt shown, but that output is in \my-org\local\eventtypes.conf
viewing the context with a hex editor, we see the same characters present

![image](https://user-images.githubusercontent.com/12401288/66245051-422f0d80-e6c0-11e9-8960-886fcb9f5bc4.png)

**Comment by SID800** [comment] 2019-10-04 23:11
As expected, once the file encoding was changed to UTF-8, this error no longer occurs.

**Comment by lowell80** [comment] 2019-10-05 00:05
Yes.  This is a bug.  I've hit it a few times but not been able to track it down.

If you still have the original, can you rerun?   Run `set KSCONF_DEBUG=1` first to enable the stack trace output and paste it here.

**Comment by SID800** [comment] 2019-10-05 13:50
```

Unhandled top-level exception.  Unexpected entry:  u'\xef\xbb\xbf###################################'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\ksconf\__main__.py", line 185, in cli
    return_code = args.funct(args)
  File "c:\python27\lib\site-packages\ksconf\commands\__init__.py", line 377, in launch
    return_code = self.run(args)
  File "c:\python27\lib\site-packages\ksconf\commands\combine.py", line 175, in run
    banner_comment=args.banner)
  File "c:\python27\lib\site-packages\ksconf\conf\merge.py", line 63, in merge_conf_files
    cfgs = [conf.data for conf in configs]
  File "c:\python27\lib\site-packages\ksconf\commands\__init__.py", line 127, in data
    self._data = self.load()
  File "c:\python27\lib\site-packages\ksconf\commands\__init__.py", line 138, in load
    data = parse_conf(self.stream, profile=parse_profile)
  File "c:\python27\lib\site-packages\ksconf\conf\parser.py", line 236, in parse_conf
    return parse_conf_stream(stream, **profile)
  File "c:\python27\lib\site-packages\ksconf\conf\parser.py", line 276, in parse_conf_stream
    for key, value in splitup_kvpairs(entry, keep_comments=keep_comments, strict=strict):
  File "c:\python27\lib\site-packages\ksconf\conf\parser.py", line 218, in splitup_kvpairs
    raise ConfParserException("Unexpected entry:  {0!r}".format(entry))
ConfParserException: Unexpected entry:  u'\xef\xbb\xbf###################################'
```

**Comment by SID800** [comment] 2019-10-10 22:10
ksconf 0.7.7rc4  (Build 452)

Another variation on the BOM character issue, I think.   local/app.conf is utf-8-bom.
The diff displays non-ascii characters.

```
C:\splunkdev\role_IT>ksconf promote local\app.conf default\app.conf
Have 1 'equal' operations:
        [launcher]  1 keys

Have 1 'replace' operations:
        [ui]

Would you like to apply ALL changes?  (y/n/d/q) d
[33;1mdiff --ksconf local\app.conf default\app.conf
[0m--- local\app.conf                                     2019-10-10 15:03:47.596239
+++ default\app.conf                                   2019-10-10 15:05:20.690130
[0m [launcher]
[0m[0m version =
[0m[0m[31m-[ui]
[31m-is_visible = 1
[0m[31m-label = IT Operations
[0m
[0m[32m+[ui]

[0mWould you like to apply ALL changes?  (y/n/d/q) y
```

**Comment by lowell80** [comment] 2020-04-24 01:28
So sorry, I just saw the last message.  It looks like your console/terminal program isn't supporting TTY escape codes.  I'm not sure the default console in Windows supports this.  The Powershell interface may, but I don't know for sure.

The other options that should work are:

1.  Unix on windows layer:  Cygwin/msys/Bash for git /WSL - although this has its own issues if you're running a Windows native python version from a unix layer shell.  ;-(. 
2. Use a "real" terminal not console.  (Less invasive).  Options include:  Cmder, PuTTY, or the new [Windows Terminal]( https://github.com/microsoft/terminal)?  I think that should work better and support TTY codes.

I'd like this to "just work" on Windows, I know there's APIs for it, but I've been hesitant to add lots of external libraries for this type of thing, but I'm open to feedback and suggestions.  And, it really seems like even Microsoft is moving away from their awful console implementation, and moving to a full fledged TTY experience for their command line platform.  And it's really tricky to detect console vs terminal at runtime, at least last time I dug into it.  But at the very least, there should be an option to disable all TTY control output.

**Comment by lowell80** [comment] 2020-04-24 01:37
I've opened #72 to track Windows console considerations; request to a disable TTY CLI option and environmental variable option too.

**Comment by lowell80** [comment] 2021-08-06 21:09
I'm about to drop support for Python 2.7, which I'm thinking is the root cause of some of these problems.  So I'm going to close this issue.  If you, or anyone else, can reproduce this in Python 3 then we can reopen.

**Closed by lowell80** 2021-08-06 21:09 UTC
Labels: bug
